<?php

namespace Kiralyta\Ntak\Enums;

use Kiralyta\Ntak\Traits\EnumToArray;

enum NTAKSummaryReason: string
{
    use EnumToArray;

    case UZEMSZUNET_ARAMSZOLGALTATAS_TERVEZETT_KIMARADASA_MIATT = 'UZEMSZUNET_ARAMSZOLGALTATAS_TERVEZETT_KIMARADASA_MIATT';
    case UZEMSZUNET_INTERNETSZOLGALTATAS_TERVEZETT_KIMARADASA_MIATT = 'UZEMSZUNET_INTERNETSZOLGALTATAS_TERVEZETT_KIMARADASA_MIATT';
    case UZEMZAVAR_ARAMSZOLGALTATAS_ATMENETI_KIMARADASA_MIATT = 'UZEMZAVAR_ARAMSZOLGALTATAS_ATMENETI_KIMARADASA_MIATT';
    case UZEMZAVAR_INTERNETSZOLGALTATAS_ATMENETI_KIMARADASA_MIATT = 'UZEMZAVAR_INTERNETSZOLGALTATAS_ATMENETI_KIMARADASA_MIATT';
    case UZEMZAVAR_TERMESZETI_KATASZTROFA_MIATT = 'UZEMZAVAR_TERMESZETI_KATASZTROFA_MIATT';
    case UZEMZAVAR_LEJART_TANUSITVANY_MIATT = 'UZEMZAVAR_LEJART_TANUSITVANY_MIATT';
    case UZEMZAVAR_MUSZAKI_HIBA_MIATT = 'UZEMZAVAR_MUSZAKI_HIBA_MIATT';
}
